### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by drom** [ucb-bar/zscale#5]
I have issues building zscale from scratch.
### Environment:

``` sh
$ uname -r
3.16.7-24-desktop
$ sbt version
[info] Set current project to zscale (in build file:/home/drom/work/github/ucb-bar/zscale/)
[info] 1.0
```
### Steps to reproduce:

``` sh
$ git clone https://github.com/ucb-bar/zscale
...
$ cd zscale
$ make
sbt -DchiselVersion=2.3-SNAPSHOT -DuncoreVersion=2.0 -DrocketVersion=1.2 compile
[info] Set current project to zscale (in build file:/home/drom/work/github/ucb-bar/zscale/)
[info] Updating {file:/home/drom/work/github/ucb-bar/zscale/}zscale...
[info] Resolving edu.berkeley.cs#chisel_2.11;2.3-SNAPSHOT ...
[warn]  module not found: edu.berkeley.cs#chisel_2.11;2.3-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/drom/.ivy2/local/edu.berkeley.cs/chisel_2.11/2.3-SNAPSHOT/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/edu/berkeley/cs/chisel_2.11/2.3-SNAPSHOT/chisel_2.11-2.3-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/edu/berkeley/cs/chisel_2.11/2.3-SNAPSHOT/chisel_2.11-2.3-SNAPSHOT.pom
[info] Resolving edu.berkeley.cs#uncore_2.11;2.0 ...
[warn]  module not found: edu.berkeley.cs#uncore_2.11;2.0
[warn] ==== local: tried
[warn]   /home/drom/.ivy2/local/edu.berkeley.cs/uncore_2.11/2.0/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/edu/berkeley/cs/uncore_2.11/2.0/uncore_2.11-2.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/edu/berkeley/cs/uncore_2.11/2.0/uncore_2.11-2.0.pom
[info] Resolving edu.berkeley.cs#rocket_2.11;1.2 ...
[warn]  module not found: edu.berkeley.cs#rocket_2.11;1.2
[warn] ==== local: tried
[warn]   /home/drom/.ivy2/local/edu.berkeley.cs/rocket_2.11/1.2/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/edu/berkeley/cs/rocket_2.11/1.2/rocket_2.11-1.2.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/edu/berkeley/cs/rocket_2.11/1.2/rocket_2.11-1.2.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: edu.berkeley.cs#chisel_2.11;2.3-SNAPSHOT: not found
[warn]  :: edu.berkeley.cs#uncore_2.11;2.0: not found
[warn]  :: edu.berkeley.cs#rocket_2.11;1.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          edu.berkeley.cs:chisel_2.11:2.3-SNAPSHOT (/home/drom/work/github/ucb-bar/zscale/build.sbt#L10-12)
[warn]            +- edu.berkeley.cs:zscale_2.11:1.0
[warn]          edu.berkeley.cs:uncore_2.11:2.0 (/home/drom/work/github/ucb-bar/zscale/build.sbt#L10-12)
[warn]            +- edu.berkeley.cs:zscale_2.11:1.0
[warn]          edu.berkeley.cs:rocket_2.11:1.2 (/home/drom/work/github/ucb-bar/zscale/build.sbt#L10-12)
[warn]            +- edu.berkeley.cs:zscale_2.11:1.0
sbt.ResolveException: unresolved dependency: edu.berkeley.cs#chisel_2.11;2.3-SNAPSHOT: not found
unresolved dependency: edu.berkeley.cs#uncore_2.11;2.0: not found
unresolved dependency: edu.berkeley.cs#rocket_2.11;1.2: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: edu.berkeley.cs#chisel_2.11;2.3-SNAPSHOT: not found
[error] unresolved dependency: edu.berkeley.cs#uncore_2.11;2.0: not found
[error] unresolved dependency: edu.berkeley.cs#rocket_2.11;1.2: not found
[error] Total time: 6 s, completed Oct 31, 2015 12:44:42 PM
Makefile:4: recipe for target 'compile' failed
make: *** [compile] Error 1
```

**Comment by sbeamer** [comment]
Like rocket, you should use https://github.com/ucb-bar/rocket-chip to build this.
